import { getStore } from '@netlify/blobs';
const STORE='crm-auth', USERS='users', SESSIONS='sessions', SESSION_DAYS=7;
const json=(body,status=200,extra={})=>new Response(JSON.stringify(body),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store',...extra}});
const b64=s=>Buffer.from(s).toString('base64url');
const rand=()=>b64(crypto.getRandomValues(new Uint8Array(32)));
const hash=async value=>b64(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(value)));
const getToken=request=>request.headers.get('cookie')?.match(/crm_session=([^;]+)/)?.[1]||request.headers.get('authorization')?.replace(/^Bearer\s+/i,'');
const publicUser=u=>({id:u.id,name:u.name,username:u.username,role:u.role});
async function getUsers(store){const users=await store.get(USERS,{type:'json'});if(Array.isArray(users)&&users.length)return users;const password=Netlify.env.get('CRM_ADMIN_PASSWORD');if(!password)return[];const admin={id:'admin',name:'Administrator',username:'admin',role:'admin',passwordHash:await hash(password)};await store.setJSON(USERS,[admin]);return[admin];}
export async function authenticate(request){const token=getToken(request);if(!token)return null;const store=getStore(STORE,{consistency:'strong'});const sessions=(await store.get(SESSIONS,{type:'json'}))||{};const s=sessions[token];if(!s||s.expiresAt<Date.now())return null;return(await getUsers(store)).find(u=>u.id===s.userId)||null;}
export default async function handler(request){try{const store=getStore(STORE,{consistency:'strong'}),users=await getUsers(store);if(request.method==='POST'){const body=await request.json(),action=body.action||'login';if(action==='login'){const username=String(body.username||'').trim().toLowerCase(),ph=await hash(String(body.password||'')),user=users.find(u=>u.username.toLowerCase()===username&&u.passwordHash===ph);if(!user)return json({error:'Invalid username or password'},401);const t=rand(),sessions=(await store.get(SESSIONS,{type:'json'}))||{};sessions[t]={userId:user.id,expiresAt:Date.now()+SESSION_DAYS*86400000};await store.setJSON(SESSIONS,sessions);return json({authenticated:true,user:publicUser(user)},200,{'set-cookie':`crm_session=${t}; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=${SESSION_DAYS*86400}`});}const actor=await authenticate(request);if(!actor||actor.role!=='admin')return json({error:'Admin access required'},403);if(action==='createCoach'){const name=String(body.name||'').trim(),username=String(body.username||'').trim().toLowerCase(),password=String(body.password||'');if(!name||!username||password.length<8)return json({error:'Name, username and an 8+ character password are required'},400);if(users.some(u=>u.username===username))return json({error:'Username already exists'},409);const coach={id:`coach_${Date.now().toString(36)}`,name,username,role:'coach',passwordHash:await hash(password)};users.push(coach);await store.setJSON(USERS,users);return json({user:publicUser(coach)},201);}return json({error:'Unknown action'},400);}if(request.method==='GET'){const user=await authenticate(request);if(!user)return json({authenticated:false},401);return json({authenticated:true,user:publicUser(user),coaches:user.role==='admin'?users.filter(u=>u.role==='coach').map(publicUser):undefined});}if(request.method==='DELETE'){const t=getToken(request),sessions=(await store.get(SESSIONS,{type:'json'}))||{};if(t)delete sessions[t];await store.setJSON(SESSIONS,sessions);return json({loggedOut:true},200,{'set-cookie':'crm_session=; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=0'});}return json({error:'Method not allowed'},405);}catch(e){return json({error:e instanceof Error?e.message:String(e)},500);}}
