import { getStore } from '@netlify/blobs';
const STORE='crm-auth',USERS='users',SESSIONS='sessions',SESSION_DAYS=7;
const json=(body,status=200,extra={})=>new Response(JSON.stringify(body),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store',...extra}});
const b64=s=>Buffer.from(s).toString('base64url');const rand=()=>b64(crypto.getRandomValues(new Uint8Array(32)));const hash=async v=>b64(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(v)));
const tokenFrom=r=>r.headers.get('cookie')?.match(/(?:^|;\s*)crm_session=([^;]+)/)?.[1]||r.headers.get('authorization')?.replace(/^Bearer\s+/i,'');
const pub=u=>({id:u.id,name:u.name,username:u.username,role:u.role});
async function getUsers(store){const u=await store.get(USERS,{type:'json'});if(Array.isArray(u)&&u.length)return u;const p=Netlify.env.get('CRM_ADMIN_PASSWORD');if(!p)return[];const a={id:'admin',name:'Administrator',username:'admin',role:'admin',passwordHash:await hash(p)};await store.setJSON(USERS,[a]);return[a];}
export async function authenticate(request){const t=tokenFrom(request);if(!t)return null;const s=getStore(STORE,{consistency:'strong'}),ss=(await s.get(SESSIONS,{type:'json'}))||{},x=ss[t];if(!x||x.expiresAt<Date.now())return null;return(await getUsers(s)).find(u=>u.id===x.userId)||null;}
export default async function handler(request){try{const store=getStore(STORE,{consistency:'strong'}),users=await getUsers(store);
if(request.method==='POST'){const b=await request.json(),action=b.action||'login';if(action==='login'){const username=String(b.username||'').trim().toLowerCase(),ph=await hash(String(b.password||'')),u=users.find(x=>x.username.toLowerCase()===username&&x.passwordHash===ph);if(!u)return json({error:'Invalid username or password'},401);const t=rand(),ss=(await store.get(SESSIONS,{type:'json'}))||{};ss[t]={userId:u.id,expiresAt:Date.now()+SESSION_DAYS*86400000};await store.setJSON(SESSIONS,ss);return json({authenticated:true,user:pub(u)},200,{'set-cookie':`crm_session=${t}; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=${SESSION_DAYS*86400}`});}const actor=await authenticate(request);if(!actor||actor.role!=='admin')return json({error:'Admin access required'},403);if(action==='createCoach'){const name=String(b.name||'').trim(),username=String(b.username||'').trim().toLowerCase(),password=String(b.password||'');if(!name||!username||password.length<8)return json({error:'Name, username and an 8+ character password are required'},400);if(users.some(u=>u.username===username))return json({error:'Username already exists'},409);const coach={id:`coach_${Date.now().toString(36)}`,name,username,role:'coach',passwordHash:await hash(password)};users.push(coach);await store.setJSON(USERS,users);return json({user:pub(coach)},201);}return json({error:'Unknown action'},400);}
if(request.method==='GET'){const u=await authenticate(request);if(!u)return json({authenticated:false},401);return json({authenticated:true,user:pub(u),coaches:u.role==='admin'?users.filter(x=>x.role==='coach').map(pub):undefined});}
if(request.method==='DELETE'){const t=tokenFrom(request),ss=(await store.get(SESSIONS,{type:'json'}))||{};if(t)delete ss[t];await store.setJSON(SESSIONS,ss);return json({loggedOut:true},200,{'set-cookie':'crm_session=; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=0'});}return json({error:'Method not allowed'},405);}catch(e){return json({error:e instanceof Error?e.message:String(e)},500);}}
