import { getStore } from '@netlify/blobs';
const STORE='crm-leads', KEY='leads';
const out=(body,status=200)=>new Response(JSON.stringify(body),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store','access-control-allow-origin':'*','access-control-allow-methods':'POST,GET,OPTIONS','access-control-allow-headers':'content-type,x-webhook-secret'}});
const str=v=>v==null?'':String(v).trim();
const first=(...xs)=>xs.find(v=>str(v)!=='');
async function parse(request){const raw=await request.text();if(!raw)return{};const ct=(request.headers.get('content-type')||'').toLowerCase();if(ct.includes('json')){try{return JSON.parse(raw)}catch{}}try{const p=new URLSearchParams(raw),o={};for(const[k,v]of p.entries())o[k]=v;return o}catch{return{raw}}}
function flatten(x){if(!x||typeof x!=='object')return[];const a=[x];for(const k of ['data','lead','contact','form','form_data','formData','fields','submission','subscriber'])if(x[k]&&typeof x[k]==='object')a.push(...flatten(x[k]));return a}
function normalize(payload){const parts=flatten(payload);let name='',email='',phone='',id='';for(const p of parts){name=first(name,p.name,p.full_name,p.fullName,p.customer_name,p.contact_name,p.first_name&&p.last_name?`${p.first_name} ${p.last_name}`:p.first_name,p['First Name'],p['Full Name']);email=first(email,p.email,p.email_address,p.emailAddress,p.Email,p['Email Address']);phone=first(phone,p.phone,p.phone_number,p.mobile,p.mobile_number,p.Phone,p.whatsapp,p.whatsapp_number,p['Phone Number'],p['Mobile Number']);id=first(id,p.id,p.lead_id,p.contact_id,p.submission_id,p.form_submission_id,p.uuid)}if(!name&&!email&&!phone)return null;const now=new Date().toISOString(),safeId=str(id)||str(email).toLowerCase()||str(phone)||`ff-${Date.now()}`;return{id:`ff-${safeId}`.replace(/[^a-zA-Z0-9_-]/g,'-').slice(0,120),name:str(name)||'New Lead',email:str(email),phone:str(phone),stage:'new',source:'5-Day Reset Challenge',ownerId:'',notes:'Captured from FlexiFunnels 5-Day Reset Challenge',createdAt:now,updatedAt:now,flexiFunnels:payload}}
export default async function handler(request){try{if(request.method==='OPTIONS')return out({ok:true});if(request.method==='GET')return out({ok:true,service:'flexifunnels-webhook',message:'Webhook is live. Send POST form submissions here.'});if(request.method!=='POST')return out({ok:false,error:'POST only'},405);const expected=Netlify.env.get('FLEXIFUNNELS_WEBHOOK_SECRET');if(expected){const supplied=request.headers.get('x-webhook-secret')||new URL(request.url).searchParams.get('secret');if(supplied!==expected)return out({ok:false,error:'Unauthorized webhook'},401)}const payload=await parse(request),lead=normalize(payload);if(!lead)return out({ok:false,error:'No lead fields found',receivedKeys:Object.keys(payload),hint:'Expected name/full_name, email, or phone/mobile'},400);const store=getStore(STORE,{consistency:'strong'}),current=(await store.get(KEY,{type:'json'}))||[],leads=Array.isArray(current)?current:[],email=lead.email.toLowerCase(),phone=lead.phone.replace(/\D/g,'');const idx=leads.findIndex(l=>(lead.flexiFunnels?.id&&l.flexiFunnels?.id===lead.flexiFunnels.id)||(email&&str(l.email).toLowerCase()===email)||(phone&&str(l.phone).replace(/\D/g,'')===phone));if(idx>=0){leads[idx]={...leads[idx],name:lead.name||leads[idx].name,email:lead.email||leads[idx].email,phone:lead.phone||leads[idx].phone,source:lead.source,updatedAt:new Date().toISOString(),flexiFunnels:lead.flexiFunnels};await store.setJSON(KEY,leads);return out({ok:true,received:true,duplicate:true,lead:leads[idx]})}leads.unshift(lead);await store.setJSON(KEY,leads);return out({ok:true,received:true,duplicate:false,lead})}catch(e){console.error('FlexiFunnels webhook error',e);return out({ok:false,error:'Unable to save lead',detail:str(e?.message||e)},500)}}
